.TH "Program Directory Reference" 3 "Sat Mar 26 2016" "Version 1.0" "Linux Kernel Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Program Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBArduinoInt\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArduinoLKM\&.c\fP"
.br
.RI "\fIA kernel module for controlling a arduino led project has 2 modes, flash or burst, (suports interruptions) and can be modified on linux user space with echo\&. \fP"
.ti -1c
.RI "file \fBArduinoLKM\&.mod\&.c\fP"
.br
.ti -1c
.RI "file \fBfileHandler\&.c\fP"
.br
.in -1c
